### ISSUE TITLE
The gzip compressed data(otw.tar.gz) may be corrupted！

### ISSUE THREAD

**Issue by xqcn** [stresearch/otw#1]
The file's information and size are as follows: 
($ `file otw.tar.gz`)
otw.tar.gz: gzip compressed data, last modified: Wed Aug 28 18:20:45 2019, from Unix
($ `ll`)  
48113762807 9月   4 11:34 otw.tar.gz

I encounter the error when try to uncompress the data. I have downloaded the file two times, so I think the original data may be corrupted.
($ `tar zxvf otw.tar.gz`)
otw/
otw/extract_frames.py
otw/homes/
otw/homes/video/
otw/homes/video/00321.mp4
otw/homes/video/00064.mp4
…… 
otw/homes/video/00016.mp4
otw/homes/video/00532.mp4
otw/homes/video/00043.mp4

**gzip: stdin: invalid compressed data--format violated
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now**

**Comment by jebyrne** [comment]
The MD5 hash of the file is:  9096bad6ff78056b505fafb4cded1734, and the size on disk should be 48113762807.  I confirmed that this hash matches for the tarball at the provided URL, and that the downloaded .tgz untars successfully.  I would recommend confirming the MD5 hash for your download, and using wget to download this file.

**Comment by xqcn** [comment]
@jebyrne Thank you for your explanation and confirmation! The MD5 hash of my file is wrong, so I download it again and get the right file. By the way, I used `wget -6 -c <...>` in the first two times but got error and for the third time I used chrome to successfully download that file.
Thank you again and sorry to bother you.
